version: '3.8'
services:
#  build the image for fastapi app
  app:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    restart: always
    container_name: ytube_server
    expose:
      - "6006"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    ports:
      - 6006:6006
    command: run_app
#  build the image for scheduler
  scheduler:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    restart: always
    container_name: ytube_scheduler
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    command: run_scheduler
#  build the image for worker
  worker:
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    restart: always
    container_name: ytube_worker
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    command: run_worker
  redis:
    image: redis:alpine
    restart: always
#   this container_name would be used inside of the pp as hostname for redis
    container_name: redis_server
    expose:
      - "6379"
    ports:
      - 6379
  postgres:
    restart: always
#   this container_name would be used inside of the pp as hostname for postgres
    container_name: postgres_db
    image: postgres:alpine
    # provide script to initiate tables
    volumes:
      - ../scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql

    # Pass postgres environment variables
    environment:
      POSTGRES_PASSWORD: zxcvbnml
      POSTGRES_DB: ytubedb
      POSTGRES_USER: ketansomvanshi
    expose:
      - "5432"
    ports:
      - 5432